version: '3.1'
services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: quincy
            POSTGRES_PASSWORD: Quincy1000
            POSTGRES_DB: medical_record_db
        volumes:
            - ./blockchain/postgres-vol:/var/lib/postgresql/data
        networks:
            - default
 
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        networks:
            - default

    mrc:
        image: mrc
        build:
            context: ./blockchain
            dockerfile: ./Dockerfile
        environment:
            FLASK_APP: medical_record_chain.py
            APP_SETTINGS: development
            SECRET: dev_secret
            DATABASE_URL: postgresql+psycopg2://quincy:Quincy1000@host.docker.internal:5432/medical_record_db
            WAIT_HOSTS: db:5432
        depends_on:
            - db
        restart: on-failure
        ports:
            - 5000:5000
        networks:
            - default

    mrcc:
        image: mrcc
        build:
            context: ./blockchain_client
            dockerfile: ./Dockerfile
        depends_on:
            - mrc
        expose:
            - 8080
        networks:
            - default

    # https://dev.to/abiodunjames/why-docker-creating-a-multi-container-application-with-docker--1gpb
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - mrcc
        ports:
            - "8080:8080"
        networks:
            - default

networks:
    default:
        driver: bridge
    
volumes:
    postgres-vol:
