"""create block table


Revision ID: d86737fb710e
Revises: e2d788e9ed7e
Create Date: 2019-03-23 07:35:18.112267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd86737fb710e'
down_revision = 'e2d788e9ed7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('transactions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('block_number')
    )
    op.drop_table('medical_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medical_records_pkey')
    )
    op.drop_table('block')
    # ### end Alembic commands ###
